export interface UsedP5Symbol {
  name: string;
  category: string;
}

const SYMBOLS: [string, string][] = [
  ['setup', 'Lifecycle'],
  ['draw', 'Lifecycle'],
  ['preload', 'Lifecycle'],
  ['windowResized', 'Lifecycle'],
  ['remove', 'Lifecycle'],
  ['mousePressed', 'Events'],
  ['mouseReleased', 'Events'],
  ['mouseClicked', 'Events'],
  ['mouseMoved', 'Events'],
  ['mouseDragged', 'Events'],
  ['mouseWheel', 'Events'],
  ['keyPressed', 'Events'],
  ['keyReleased', 'Events'],
  ['keyTyped', 'Events'],
  ['touchStarted', 'Events'],
  ['touchMoved', 'Events'],
  ['touchEnded', 'Events'],
  ['deviceMoved', 'Events'],
  ['deviceTurned', 'Events'],
  ['deviceShaken', 'Events'],
  ['loadJSON', 'I/O'],
  ['loadStrings', 'I/O'],
  ['loadXML', 'I/O'],
  ['loadTable', 'I/O'],
  ['saveJSON', 'I/O'],
  ['saveStrings', 'I/O'],
  ['saveTable', 'I/O'],
  ['save', 'I/O'],
  ['httpGet', 'I/O'],
  ['httpPost', 'I/O'],
  ['httpDo', 'I/O'],
  ['translate', 'Transform'],
  ['rotate', 'Transform'],
  ['rotateX', 'Transform'],
  ['rotateY', 'Transform'],
  ['rotateZ', 'Transform'],
  ['scale', 'Transform'],
  ['shearX', 'Transform'],
  ['shearY', 'Transform'],
  ['pushMatrix', 'Transform'],
  ['popMatrix', 'Transform'],
  ['resetMatrix', 'Transform'],
  ['applyMatrix', 'Transform'],
  ['fill', 'Color & Style'],
  ['noFill', 'Color & Style'],
  ['stroke', 'Color & Style'],
  ['noStroke', 'Color & Style'],
  ['background', 'Color & Style'],
  ['color', 'Color & Style'],
  ['colorMode', 'Color & Style'],
  ['erase', 'Color & Style'],
  ['noErase', 'Color & Style'],
  ['blendMode', 'Color & Style'],
  ['angleMode', 'Color & Style'],
  ['ellipseMode', 'Color & Style'],
  ['rectMode', 'Color & Style'],
  ['strokeCap', 'Color & Style'],
  ['strokeJoin', 'Color & Style'],
  ['strokeWeight', 'Color & Style'],
  ['smooth', 'Color & Style'],
  ['noSmooth', 'Color & Style'],
  ['ellipse', 'Shape'],
  ['circle', 'Shape'],
  ['arc', 'Shape'],
  ['rect', 'Shape'],
  ['square', 'Shape'],
  ['line', 'Shape'],
  ['triangle', 'Shape'],
  ['quad', 'Shape'],
  ['point', 'Shape'],
  ['beginShape', 'Shape'],
  ['endShape', 'Shape'],
  ['vertex', 'Shape'],
  ['curveVertex', 'Shape'],
  ['quadraticVertex', 'Shape'],
  ['bezierVertex', 'Shape'],
  ['contour', 'Shape'],
  ['beginContour', 'Shape'],
  ['endContour', 'Shape'],
  ['curve', 'Shape'],
  ['bezier', 'Shape'],
  ['curveDetail', 'Shape'],
  ['curveTightness', 'Shape'],
  ['curvePoint', 'Shape'],
  ['curveTangent', 'Shape'],
  ['bezierPoint', 'Shape'],
  ['bezierTangent', 'Shape'],
  ['texture', 'Shape'],
  ['textureMode', 'Shape'],
  ['textureWrap', 'Shape'],
  ['abs', 'Math'],
  ['ceil', 'Math'],
  ['constrain', 'Math'],
  ['dist', 'Math'],
  ['exp', 'Math'],
  ['floor', 'Math'],
  ['fract', 'Math'],
  ['lerp', 'Math'],
  ['log', 'Math'],
  ['mag', 'Math'],
  ['map', 'Math'],
  ['max', 'Math'],
  ['min', 'Math'],
  ['norm', 'Math'],
  ['pow', 'Math'],
  ['round', 'Math'],
  ['sq', 'Math'],
  ['sqrt', 'Math'],
  ['noise', 'Math'],
  ['noiseDetail', 'Math'],
  ['noiseSeed', 'Math'],
  ['random', 'Math'],
  ['randomSeed', 'Math'],
  ['randomGaussian', 'Math'],
  ['sin', 'Math'],
  ['cos', 'Math'],
  ['tan', 'Math'],
  ['atan', 'Math'],
  ['atan2', 'Math'],
  ['asin', 'Math'],
  ['acos', 'Math'],
  ['degrees', 'Math'],
  ['radians', 'Math'],
  ['text', 'Typography'],
  ['textFont', 'Typography'],
  ['textSize', 'Typography'],
  ['textStyle', 'Typography'],
  ['textAlign', 'Typography'],
  ['textWidth', 'Typography'],
  ['textAscent', 'Typography'],
  ['textDescent', 'Typography'],
  ['textLeading', 'Typography'],
  ['textWrap', 'Typography'],
  ['loadFont', 'Typography'],
  ['createCanvas', 'Rendering'],
  ['resizeCanvas', 'Rendering'],
  ['noCanvas', 'Rendering'],
  ['createGraphics', 'Rendering'],
  ['setAttributes', 'Rendering'],
  ['pixelDensity', 'Rendering'],
  ['displayDensity', 'Rendering'],
  ['print', 'Rendering'],
  ['println', 'Rendering'],
  ['clear', 'Rendering'],
  ['image', 'Image'],
  ['createImage', 'Image'],
  ['loadImage', 'Image'],
  ['imageMode', 'Image'],
  ['loadPixels', 'Image'],
  ['updatePixels', 'Image'],
  ['filter', 'Image'],
  ['blend', 'Image'],
  ['copy', 'Image'],
  ['get', 'Image'],
  ['resize', 'Image'],
  ['saveCanvas', 'Image'],
  ['saveFrames', 'Image'],
  ['ambientLight', 'Lights & Camera'],
  ['directionalLight', 'Lights & Camera'],
  ['pointLight', 'Lights & Camera'],
  ['spotLight', 'Lights & Camera'],
  ['lights', 'Lights & Camera'],
  ['noLights', 'Lights & Camera'],
  ['lightFalloff', 'Lights & Camera'],
  ['camera', 'Lights & Camera'],
  ['createCamera', 'Lights & Camera'],
  ['setCamera', 'Lights & Camera'],
  ['orbitControl', 'Lights & Camera'],
  ['debugMode', 'Lights & Camera'],
  ['noDebug', 'Lights & Camera'],
  ['perspective', 'Lights & Camera'],
  ['ortho', 'Lights & Camera'],
  ['createShader', 'Shaders'],
  ['loadShader', 'Shaders'],
  ['shader', 'Shaders'],
  ['resetShader', 'Shaders'],
  ['createVector', 'Vector'],
  ['fromAngle', 'Vector'],
  ['normalize', 'Vector'],
  ['setMag', 'Vector'],
  ['limit', 'Vector'],
  ['heading', 'Vector'],
  ['angleBetween', 'Vector'],
  ['dot', 'Vector'],
  ['cross', 'Vector'],
  ['random2D', 'Vector'],
  ['random3D', 'Vector'],
  ['select', 'DOM'],
  ['selectAll', 'DOM'],
  ['drop', 'DOM'],
  ['parent', 'DOM'],
  ['style', 'DOM'],
  ['position', 'DOM'],
  ['show', 'DOM'],
  ['hide', 'DOM'],
  ['addClass', 'DOM'],
  ['removeClass', 'DOM'],
  ['toggleClass', 'DOM'],
  ['child', 'DOM'],
  ['attribute', 'DOM'],
  ['value', 'DOM'],
  ['html', 'DOM'],
  ['center', 'DOM'],
  ['createP', 'DOM'],
  ['createDiv', 'DOM'],
  ['createSpan', 'DOM'],
  ['createInput', 'DOM'],
  ['createButton', 'DOM'],
  ['createCheckbox', 'DOM'],
  ['createSelect', 'DOM'],
  ['createRadio', 'DOM'],
  ['createSlider', 'DOM'],
  ['createColorPicker', 'DOM'],
  ['createFileInput', 'DOM'],
  ['createVideo', 'DOM'],
  ['createAudio', 'DOM'],
  ['createCapture', 'DOM'],
  ['createWriter', 'DOM'],
  ['userStartAudio', 'Sound'],
  ['getAudioContext', 'Sound'],
  ['soundFormats', 'Sound'],
  ['loadSound', 'Sound'],
  ['PI', 'Constants'],
  ['TWO_PI', 'Constants'],
  ['HALF_PI', 'Constants'],
  ['QUARTER_PI', 'Constants'],
  ['TAU', 'Constants'],
  ['width', 'Properties'],
  ['height', 'Properties'],
  ['mouseX', 'Properties'],
  ['mouseY', 'Properties'],
  ['mouseButton', 'Properties'],
  ['mouseIsPressed', 'Properties'],
  ['key', 'Properties'],
  ['keyCode', 'Properties'],
  ['keyIsPressed', 'Properties'],
  ['frameCount', 'Properties'],
  ['frameRate', 'Properties'],
  ['displayWidth', 'Properties'],
  ['displayHeight', 'Properties'],
  ['windowWidth', 'Properties'],
  ['windowHeight', 'Properties'],
  ['pixelDensity', 'Properties'],
  ['focused', 'Properties'],
];

export function findUsedP5Symbols(code: string): UsedP5Symbol[] {
  const result: UsedP5Symbol[] = [];
  const seen = new Set<string>();

  for (const [name, category] of SYMBOLS) {
    if (seen.has(name)) continue;
    const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const pattern = new RegExp(`\\b${escaped}\\b`);
    if (pattern.test(code)) {
      result.push({ name, category });
      seen.add(name);
    }
  }

  return result;
}
